macro(CheckFileDialogBackend)

  set(BACKEND "dummy")
  if (WIN32 OR WINDOWS OR CYGWIN)
    set(BACKEND "win32")
  endif()
  if (APPLE AND NOT IPHONEOS)
    set(BACKEND "cocoa")
  endif()
  if (UNIX AND NOT APPLE OR ANDROID)
    find_package(PkgConfig)
    if (PKG_CONFIG_FOUND)
      pkg_check_modules(GTK "gtk+-3.0")
      if (GTK_FOUND)
        set(BACKEND "gtk")
      endif()
    endif()
  endif()

  if ("${BACKEND}" STREQUAL "win32")
    add_definitions("-DFILEDIALOG_WIN32")
    set(LIBS ${LIBS} -mwindows)
  endif()

  if ("${BACKEND}" STREQUAL "cocoa")
    add_definitions("-DFILEDIALOG_COCOA")
    set(LIBS ${LIBS} -Wl,-framework,Cocoa)
    set(EXTRA_SOURCES "${CMAKE_SOURCE_DIR}/src/filedialog/SDLU_filedialog_cocoa.m")
  endif()

  if ("${BACKEND}" STREQUAL "gtk")
    add_definitions("-DFILEDIALOG_GTK")
    set(LIBS ${GTK_LIBRARIES})
    include_directories(${GTK_INCLUDE_DIRS})
    add_definitions(${GTK_CFLAGS} ${GTK_CFLAGS_OTHER})
  endif()

  if ("${BACKEND}" STREQUAL "dummy")
    add_definitions("-DFILEDIALOG_DUMMY")
  endif()

endmacro()
