if (APPLE)
  set(SDLTTF_SOURCES "${CMAKE_SOURCE_DIR}/external/freetype2/ftmac.c")
endif(APPLE)

set(SDLTTF_SOURCES ${SDLTTF_SOURCES}
  "${CMAKE_SOURCE_DIR}/external/freetype2/autofit.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftbase.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftbbox.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftbdf.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftbitmap.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftcid.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftdebug.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftfstype.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftgasp.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftglyph.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftgxval.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftinit.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftlcdfil.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftmm.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftotval.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftpatent.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftpfr.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftstroke.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftsynth.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftsystem.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/fttype1.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftwinfnt.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftxf86.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/bdf.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftbzip2.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftcache.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/cff.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/type1cid.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftgzip.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/ftlzw.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/pcf.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/pfr.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/psaux.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/pshinter.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/psmodule.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/raster.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/sfnt.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/smooth.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/apinames.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/truetype.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/type1.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/type42.c"
  "${CMAKE_SOURCE_DIR}/external/freetype2/winfnt.c"
  "${CMAKE_SOURCE_DIR}/external/sdl_ttf/SDL_ttf.c"
)

