#! /bin/bash

## Use this script to generate configure and Makefile.in
## Known working autotools versions:
##  * autoconf  2.69
##  * automake  1.14
##  * libtool   2.4.2

wd=`dirname $0`
wd=`cd $wd && echo $PWD`
wd=`cd $wd/.. && echo $PWD`

cd $wd      && autoreconf --force --install && rm -rf $wd/autom4te.cache
cd $wd/test && autoreconf --force --install && rm -rf $wd/test/autom4te.cache

echo "You are now ready to run ./configure"
